# Generated by Django 5.0.7 on 2024-07-26 06:09

import Task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=Task.models.one_week_hence),
        ),
    ]
